// @codekit-append '../bower_components/modernizr/modernizr.js'
// @codekit-append '../bower_components/modernizr/feature-detects/forms-formattribute.js'
// @codekit-append '../bower_components/modernizr/feature-detects/css-vhunit.js'
// @codekit-append '../bower_components/detectizr/src/detectizr.js'
// @codekit-append 'ie-shims.js'